name: Generate iOS Certs

# NOTE FOR FUTURE ME
# 
# We conceptually only want to run this after our one-time setup.
# The setup step adds a deploy key to our secrets, and we need access to that deploy key.
#
# Unfortunately, GitHub Actions seems to fetch "secrets" once, when first parsing a .yml file
# This means, if we shove these two jobs into the same file, this second job doesn't have access to
# the not-created-yet secret.
# 
# Two possible long-term solutions here:
# 1. Make the "iOS One-Time Setup" job export the deploy key as an output.
#    This would unfortunately involve updating the fastlane plugin to output the key as an env var, 
#    then add an additional command to output that env var as a step output
# 2. Make this workflow job make a GitHub API call to fetch the match deploy key
#    Since we already have a valid personal access token in this workflow, 
#    This seems less effortful than something requiring an upstream PR to a third-party library

on:
  workflow_run:
    workflows: ["iOS One-Time Setup"]
    types:
      - completed
  workflow_dispatch:

jobs:
  generate_certs:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6
          bundler-cache: true 

      - name: Build iOS
        shell: bash
        run: |
          eval "$(ssh-agent -s)"
          ssh-add - <<< "${MATCH_DEPLOY_KEY}"
          bundle exec fastlane sync_certificates
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
          MATCH_REPOSITORY: ${{ secrets.MATCH_REPOSITORY }}
          GITHUB_REPOSITORY: ${{ env.GITHUB_REPOSITORY }}
          APP_STORE_CONNECT_KEY_ID: ${{ secrets.APP_STORE_CONNECT_KEY_ID }}
          APP_STORE_CONNECT_ISSUER_ID: ${{ secrets.APP_STORE_CONNECT_ISSUER_ID }}
          APP_STORE_CONNECT_KEY: ${{ secrets.APP_STORE_CONNECT_KEY }} # Raw .p8 value
          MATCH_DEPLOY_KEY: ${{ secrets.MATCH_DEPLOY_KEY }}
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}

          BUNDLE_ID: ${{ secrets.BUNDLE_ID }} # TODO: Read this from Unity project